version: "3.9"

services:
  server:
    build: ./server
    container_name: api
    ports:
      - "39101:39101"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  client:
    build: ./client
    container_name: ui
    ports:
      - "35179:35179"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server